const colors = require('tailwindcss/colors')

module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        'bluegray': colors.blueGray,
        'coolgray': colors.coolGray,
        'truegray': colors.trueGray,
        'warmgray': colors.warmGray,
        'orange': colors.orange,
        'amber': colors.amber,
        'lime': colors.lime,
        'emerald': colors.emerald,
        'teal': colors.teal,
        'cyan': colors.cyan,
        'sky': colors.sky,
        'violet': colors.violet,
        'fuchsia': colors.fuchsia,
        'rose': colors.rose
      },
      fontFamily: {
        'roboto': ['Roboto', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
        'lato': ['Lato', 'sans-serif'],
        'montserrat': ['Montserrat', 'sans-serif'],
        'source-sans-pro': ['Source Sans Pro', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'oswald': ['Oswald', 'sans-serif'],
        'league-spartan-bold': ['League Spartan Bold', 'sans-serif'],
        'raleway': ['Raleway', 'sans-serif'],
        'nunito': ['Nunito', 'sans-serif'],
        'ubuntu': ['Ubuntu', 'sans-serif'],
        'pt-sans': ['PT Sans', 'sans-serif'],
        'titillium-web': ['Titillium Web', 'sans-serif'],
        'comfortaa': ['Comfortaa', 'sans-serif'],
        'merriweather': ['Merriweather', 'serif'],
        'playfair-display': ['Playfair Display', 'serif'],
        'lora': ['Lora', 'serif'],
        'noto-serif': ['Noto Serif', 'serif'],
        'libre-baskerville': ['Lora', 'serif'],
        'bitter': ['Bitter', 'serif'],
        'crimson-text': ['Crimson Text', 'serif'],
        'arvo': ['Arvo', 'serif'],
        'domine': ['Domine', 'serif'],
        'cinzel': ['Cinzel', 'serif'],
        'bebas-neue': ['Bebas Neue', 'cursive'],
        'lobster': ['Lobster', 'cursive'],
        'balsamiq-sans': ['Balsamiq Sans', 'cursive'],
        'abril-fatface': ['Abril Fatface', 'cursive'],
        'alfa-slab-one': ['Alfa Slab One', 'cursive'],
        'patua-one': ['Patua One', 'cursive'],
        'righteous': ['Righteous', 'cursive'],
        'fredoka-one': ['Fredoka One', 'cursive'],
        'staatliches': ['Staatliches', 'cursive'],
        'luckiest-guy': ['Luckiest Guy', 'cursive'],
        'special-elite': ['Special Elite', 'cursive'],
        'sigmar-one': ['Sigmar one', 'cursive'],
        'playball': ['Playball', 'cursive'],
        'bangers': ['Bangers', 'cursive'],
        'dancing-script': ['Dancing Script', 'cursive'],
        'pacifico': ['Pacifico', 'cursive'],
        'indie-flower': ['Indie Flower', 'cursive'],
        'shadows-into-light': ['Shadows Into Light', 'cursive'],
        'patrick-hand': ['Patrick Hand', 'cursive'],
        'permanent-marker': ['Permanent Marker', 'cursive'],
        'caveat': ['Caveat', 'cursive'],
        'satisfy': ['Satisfy', 'cursive'],
        'amatic-sc': ['Amatic SC', 'cursive'],
        'cookie': ['Cookie', 'cursive'],
        'great-vibes': ['Great Vibes', 'cursive'],
        'fredericka-the-great': ['Fredericka the Great', 'cursive'],
      }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}